=== api-evangelist/tmdb/json-schema/tmdb-api-find-by-id-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/tmdb/refs/heads/main/json-schema/tmdb-api-find-by-id-response-schema.json",
  "title": "FindByIdResponse",
  "description": "TMDB Find \u2014 Find by ID (200 payload).",
  "type": "object",
  "properties": {
    "movie_results": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "adult": {
            "type": "boolean",
            "examples": [
              false
            ],
            "default": true
          },
          "backdrop_path": {
            "type": "string",
            "examples": [
              "/44immBwzhDVyjn87b3x3l9mlhAD.jpg"
            ]
          },
          "id": {
            "type": "integer",
            "examples": [
              934433
            ],
            "default": 0
          },
          "title": {
            "type": "string",
            "examples": [
              "Scream VI"
            ]
          },
          "original_language": {
            "type": "string",
            "examples": [
              "en"
            ]
          },
          "original_title": {
            "type": "string",
            "examples": [
              "Scream VI"
            ]
          },
          "overview": {
            "type": "string",
            "examples": [
              "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter."
            ]
          },
          "poster_path": {
            "type": "string",
            "examples": [
              "/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg"
            ]
          },
          "media_type": {
            "type": "string",
            "examples": [
              "movie"
            ]
          },
          "genre_ids": {
            "type": "array",
            "items": {
              "type": "integer",
              "examples": [
                27
              ],
              "default": 0
            }
          },
          "popularity": {
            "type": "number",
            "examples": [
              853.917
            ],
            "default": 0
          },
          "release_date": {
            "type": "string",
            "examples": [
              "2023-03-08"
            ]
          },
          "video": {
            "type": "boolean",
            "examples": [
              false
            ],
            "default": true
          },
          "vote_average": {
            "type": "number",
            "examples": [
              7.388
            ],
            "default": 0
          },
          "vote_count": {
            "type": "integer",
            "examples": [
              708
            ],
            "default": 0
          }
        }
      }
    },
    "person_results": {
      "type": "array"
    },
    "tv_results": {
      "type": "array"
    },
    "tv_episode_results": {
      "type": "array"
    },
    "tv_season_results": {
      "type": "array"
    }
  }
}

=== api-evangelist/tmdb/examples/tmdb-api-find-by-id-response-example.json
{
  "movie_results": [
    {
      "adult": false,
      "backdrop_path": "/44immBwzhDVyjn87b3x3l9mlhAD.jpg",
      "id": 934433,
      "title": "Scream VI",
      "original_language": "en",
      "original_title": "Scream VI",
      "overview": "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
      "poster_path": "/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
      "media_type": "movie",
      "genre_ids": [
        27
      ],
      "popularity": 853.917,
      "release_date": "2023-03-08",
      "video": false,
      "vote_average": 7.388,
      "vote_count": 708
    }
  ],
  "person_results": [
    {}
  ],
  "tv_results": [
    {}
  ],
  "tv_episode_results": [
    {}
  ],
  "tv_season_results": [
    {}
  ]
}
