=== api-evangelist/tmdb/json-schema/tmdb-api-lists-copy-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/tmdb/refs/heads/main/json-schema/tmdb-api-lists-copy-response-schema.json",
  "title": "ListsCopyResponse",
  "description": "TMDB TV Series \u2014 Lists (200 payload).",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "examples": [
        1399
      ],
      "default": 0
    },
    "page": {
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "results": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "examples": [
              ""
            ]
          },
          "favorite_count": {
            "type": "integer",
            "examples": [
              0
            ],
            "default": 0
          },
          "id": {
            "type": "integer",
            "examples": [
              8257231
            ],
            "default": 0
          },
          "item_count": {
            "type": "integer",
            "examples": [
              182
            ],
            "default": 0
          },
          "iso_639_1": {
            "type": "string",
            "examples": [
              "en"
            ]
          },
          "iso_3166_1": {
            "type": "string",
            "examples": [
              "US"
            ]
          },
          "name": {
            "type": "string",
            "examples": [
              "Done"
            ]
          },
          "poster_path": {}
        }
      }
    },
    "total_pages": {
      "type": "integer",
      "examples": [
        96
      ],
      "default": 0
    },
    "total_results": {
      "type": "integer",
      "examples": [
        1906
      ],
      "default": 0
    }
  }
}

=== api-evangelist/tmdb/examples/tmdb-api-movie-lists-response-example.json
{
  "id": 550,
  "page": 1,
  "results": [
    {
      "description": "Movies I own",
      "favorite_count": 0,
      "id": 8248696,
      "item_count": 409,
      "iso_639_1": "en",
      "list_type": "movie",
      "name": "My Movies",
      "poster_path": {}
    }
  ],
  "total_pages": 122,
  "total_results": 2422
}

=== api-evangelist/tmdb/examples/tmdb-api-keyword-movies-response-example.json
{
  "id": 1701,
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/3CxUndGhUcZdt1Zggjdb2HkLLQX.jpg",
      "genre_ids": [
        28
      ],
      "id": 640146,
      "original_language": "en",
      "original_title": "Ant-Man and the Wasp: Quantumania",
      "overview": "Das Superhelden-Duo Scott Lang und Hope Van Dyne erkundet zusammen mit Hopes Eltern Hank Pym und Janet Van Dyne das Quantenreich, interagiert mit seltsamen neuen Kreaturen und begibt sich auf ein Abenteuer, das sie \u00fcber die Grenzen dessen hinaustreiben wird, was sie f\u00fcr m\u00f6glich gehalten haben.",
      "popularity": 9200.005,
      "poster_path": "/nA5otwVxAfpBP4PVgeuBk3qHcLY.jpg",
      "release_date": "2023-02-15",
      "title": "Ant-Man and the Wasp: Quantumania",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 2079
    }
  ],
  "total_pages": 11,
  "total_results": 211
}

=== api-evangelist/tmdb/examples/tmdb-api-lists-copy-response-example.json
{
  "id": 1399,
  "page": 1,
  "results": [
    {
      "description": "",
      "favorite_count": 0,
      "id": 8257231,
      "item_count": 182,
      "iso_639_1": "en",
      "iso_3166_1": "US",
      "name": "Done",
      "poster_path": {}
    }
  ],
  "total_pages": 96,
  "total_results": 1906
}
