=== api-evangelist/tmdb/json-schema/tmdb-api-movie-now-playing-list-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/tmdb/refs/heads/main/json-schema/tmdb-api-movie-now-playing-list-response-schema.json",
  "title": "MovieNowPlayingListResponse",
  "description": "TMDB Movies \u2014 Now Playing (200 payload).",
  "type": "object",
  "properties": {
    "dates": {
      "type": "object",
      "properties": {
        "maximum": {
          "type": "string",
          "examples": [
            "2023-05-03"
          ]
        },
        "minimum": {
          "type": "string",
          "examples": [
            "2023-03-16"
          ]
        }
      }
    },
    "page": {
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "results": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "adult": {
            "type": "boolean",
            "examples": [
              false
            ],
            "default": true
          },
          "backdrop_path": {
            "type": "string",
            "examples": [
              "/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg"
            ]
          },
          "genre_ids": {
            "type": "array",
            "items": {
              "type": "integer",
              "examples": [
                16
              ],
              "default": 0
            }
          },
          "id": {
            "type": "integer",
            "examples": [
              502356
            ],
            "default": 0
          },
          "original_language": {
            "type": "string",
            "examples": [
              "en"
            ]
          },
          "original_title": {
            "type": "string",
            "examples": [
              "The Super Mario Bros. Movie"
            ]
          },
          "overview": {
            "type": "string",
            "examples": [
              "While working underground to fix a water main, Brooklyn plumbers\u2014and brothers\u2014Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi."
            ]
          },
          "popularity": {
            "type": "number",
            "examples": [
              6572.614
            ],
            "default": 0
          },
          "poster_path": {
            "type": "string",
            "examples": [
              "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg"
            ]
          },
          "release_date": {
            "type": "string",
            "examples": [
              "2023-04-05"
            ]
          },
          "title": {
            "type": "string",
            "examples": [
              "The Super Mario Bros. Movie"
            ]
          },
          "video": {
            "type": "boolean",
            "examples": [
              false
            ],
            "default": true
          },
          "vote_average": {
            "type": "number",
            "examples": [
              7.5
            ],
            "default": 0
          },
          "vote_count": {
            "type": "integer",
            "examples": [
              1456
            ],
            "default": 0
          }
        }
      }
    },
    "total_pages": {
      "type": "integer",
      "examples": [
        87
      ],
      "default": 0
    },
    "total_results": {
      "type": "integer",
      "examples": [
        1734
      ],
      "default": 0
    }
  }
}

=== api-evangelist/tmdb/examples/tmdb-api-movie-now-playing-list-response-example.json
{
  "dates": {
    "maximum": "2023-05-03",
    "minimum": "2023-03-16"
  },
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg",
      "genre_ids": [
        16
      ],
      "id": 502356,
      "original_language": "en",
      "original_title": "The Super Mario Bros. Movie",
      "overview": "While working underground to fix a water main, Brooklyn plumbers\u2014and brothers\u2014Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
      "popularity": 6572.614,
      "poster_path": "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
      "release_date": "2023-04-05",
      "title": "The Super Mario Bros. Movie",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 1456
    }
  ],
  "total_pages": 87,
  "total_results": 1734
}

=== api-evangelist/tmdb/examples/tmdb-api-movie-upcoming-list-response-example.json
{
  "dates": {
    "maximum": "2023-05-23",
    "minimum": "2023-05-04"
  },
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg",
      "genre_ids": [
        27
      ],
      "id": 713704,
      "original_language": "en",
      "original_title": "Evil Dead Rise",
      "overview": "Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
      "popularity": 1696.367,
      "poster_path": "/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
      "release_date": "2023-04-12",
      "title": "Evil Dead Rise",
      "video": false,
      "vote_average": 7,
      "vote_count": 207
    }
  ],
  "total_pages": 19,
  "total_results": 369
}
