=== api-evangelist/tmdb/json-schema/tmdb-api-movie-reviews-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/tmdb/refs/heads/main/json-schema/tmdb-api-movie-reviews-response-schema.json",
  "title": "MovieReviewsResponse",
  "description": "TMDB Movies \u2014 Reviews (200 payload).",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "examples": [
        550
      ],
      "default": 0
    },
    "page": {
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "results": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "author": {
            "type": "string",
            "examples": [
              "Goddard"
            ]
          },
          "author_details": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "examples": [
                  ""
                ]
              },
              "username": {
                "type": "string",
                "examples": [
                  "Goddard"
                ]
              },
              "avatar_path": {
                "type": "string",
                "examples": [
                  "/https://secure.gravatar.com/avatar/f248ec34f953bc62cafcbdd81fddd6b6.jpg"
                ]
              },
              "rating": {}
            }
          },
          "content": {
            "type": "string",
            "examples": [
              "Pretty awesome movie.  It shows what one crazy person can convince other crazy people to do.  Everyone needs something to believe in.  I recommend Jesus Christ, but they want Tyler Durden."
            ]
          },
          "created_at": {
            "type": "string",
            "examples": [
              "2018-06-09T17:51:53.359Z"
            ]
          },
          "id": {
            "type": "string",
            "examples": [
              "5b1c13b9c3a36848f2026384"
            ]
          },
          "updated_at": {
            "type": "string",
            "examples": [
              "2021-06-23T15:58:09.421Z"
            ]
          },
          "url": {
            "type": "string",
            "examples": [
              "https://www.themoviedb.org/review/5b1c13b9c3a36848f2026384"
            ]
          }
        }
      }
    },
    "total_pages": {
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "total_results": {
      "type": "integer",
      "examples": [
        8
      ],
      "default": 0
    }
  }
}

=== api-evangelist/tmdb/examples/tmdb-api-person-tagged-images-response-example.json
{
  "id": 31,
  "page": 1,
  "results": [
    {
      "aspect_ratio": 0.6666666666666666,
      "file_path": "/1wY4psJ5NVEhCuOYROwLH2XExM2.jpg",
      "height": 1500,
      "id": "5b235d740e0a265b5d0031d9",
      "iso_639_1": "en",
      "vote_average": 5.456,
      "vote_count": 7,
      "width": 1000,
      "image_type": "poster",
      "media": {
        "adult": false,
        "backdrop_path": "/bdD39MpSVhKjxarTxLSfX6baoMP.jpg",
        "id": 857,
        "title": "Saving Private Ryan",
        "original_language": "en",
        "original_title": "Saving Private Ryan",
        "overview": "As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.",
        "poster_path": "/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
        "media_type": "movie",
        "genre_ids": [
          {}
        ],
        "popularity": 70.45,
        "release_date": "1998-07-24",
        "video": false,
        "vote_average": 8.208,
        "vote_count": 14134
      },
      "media_type": "movie"
    }
  ],
  "total_pages": 1,
  "total_results": 13
}

=== api-evangelist/tmdb/examples/tmdb-api-tv-series-reviews-response-example.json
{
  "id": 1399,
  "page": 1,
  "results": [
    {
      "author": "lmao7",
      "author_details": {
        "name": "lmao7",
        "username": "lmao7",
        "avatar_path": "/ekmYOUU4tfx9zGGadjRdE7UPce.jpg",
        "rating": 9
      },
      "content": "I started watching when it came out as I heard that fans of LOTR also liked this. I stopped watching after Season 1 as I was devastated lol kinda. Only 2015 I decided to continue watching and got addicted like it seemed complicated at first, too many stories and characters. I even used a guide from internet like family tree per house while watching or GOT wiki so I can have more background on the characters. For a TV series, this show can really take you to a different world and never knowing what will happen. It is very daring that any time anybody can just die (I learned not to be attached and have accepted that they will all die so I won't be devastated hehe). I have never read the books but the show is entertaining and you will really root for your faves and really hate on those you hate. \r\n\r\nFantasy, action, drama, comedy, love...and lots of surprises!",
      "created_at": "2017-02-20T05:47:28.872Z",
      "id": "58aa82f09251416f92006a3a",
      "updated_at": "2021-06-23T15:57:54.649Z",
      "url": "https://www.themoviedb.org/review/58aa82f09251416f92006a3a"
    }
  ],
  "total_pages": 1,
  "total_results": 11
}

=== api-evangelist/tmdb/examples/tmdb-api-movie-reviews-response-example.json
{
  "id": 550,
  "page": 1,
  "results": [
    {
      "author": "Goddard",
      "author_details": {
        "name": "",
        "username": "Goddard",
        "avatar_path": "/https://secure.gravatar.com/avatar/f248ec34f953bc62cafcbdd81fddd6b6.jpg",
        "rating": {}
      },
      "content": "Pretty awesome movie.  It shows what one crazy person can convince other crazy people to do.  Everyone needs something to believe in.  I recommend Jesus Christ, but they want Tyler Durden.",
      "created_at": "2018-06-09T17:51:53.359Z",
      "id": "5b1c13b9c3a36848f2026384",
      "updated_at": "2021-06-23T15:58:09.421Z",
      "url": "https://www.themoviedb.org/review/5b1c13b9c3a36848f2026384"
    }
  ],
  "total_pages": 1,
  "total_results": 8
}
