=== api-evangelist/tmdb/json-schema/tmdb-api-account-lists-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/tmdb/refs/heads/main/json-schema/tmdb-api-account-lists-response-schema.json",
  "title": "AccountListsResponse",
  "description": "TMDB Account \u2014 Lists (200 payload).",
  "type": "object",
  "properties": {
    "page": {
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "results": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "examples": [
              ""
            ]
          },
          "favorite_count": {
            "type": "integer",
            "examples": [
              0
            ],
            "default": 0
          },
          "id": {
            "type": "integer",
            "examples": [
              120174
            ],
            "default": 0
          },
          "item_count": {
            "type": "integer",
            "examples": [
              5
            ],
            "default": 0
          },
          "iso_639_1": {
            "type": "string",
            "examples": [
              "en"
            ]
          },
          "list_type": {
            "type": "string",
            "examples": [
              "movie"
            ]
          },
          "name": {
            "type": "string",
            "examples": [
              "Test Alpha Sort"
            ]
          },
          "poster_path": {}
        }
      }
    },
    "total_pages": {
      "type": "integer",
      "examples": [
        2
      ],
      "default": 0
    },
    "total_results": {
      "type": "integer",
      "examples": [
        25
      ],
      "default": 0
    }
  }
}

=== api-evangelist/tmdb/examples/tmdb-api-account-watchlist-tv-response-example.json
{
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/7phlGHRupo38EnuwmkAHdNUqov3.jpg",
      "genre_ids": [
        35
      ],
      "id": 58932,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "The Crazy Ones",
      "overview": "The Crazy Ones is an American situation comedy series created by David E. Kelley that stars Robin Williams and Sarah Michelle Gellar. The single-camera project premiered on CBS on September 26, 2013, as part of the 2013\u201314 American television season as a Thursday night 9 pm entry. Bill D'Elia, Dean Lorey, Jason Winer, John Montgomery and Mark Teitelbaum serve as executive producers for 20th Century Fox Television.",
      "popularity": 8.939,
      "poster_path": "/s2e7hTrdmNUaJDf0yDP5b4AHvrD.jpg",
      "first_air_date": "2013-09-26",
      "name": "The Crazy Ones",
      "vote_average": 6.176,
      "vote_count": 94
    }
  ],
  "total_pages": 17,
  "total_results": 325
}

=== api-evangelist/tmdb/examples/tmdb-api-trending-all-response-example.json
{
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/44immBwzhDVyjn87b3x3l9mlhAD.jpg",
      "id": 934433,
      "title": "Scream VI",
      "original_language": "en",
      "original_title": "Scream VI",
      "overview": "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
      "poster_path": "/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
      "media_type": "movie",
      "genre_ids": [
        27
      ],
      "popularity": 609.941,
      "release_date": "2023-03-08",
      "video": false,
      "vote_average": 7.374,
      "vote_count": 684
    }
  ],
  "total_pages": 1000,
  "total_results": 20000
}

=== api-evangelist/tmdb/examples/tmdb-api-movie-similar-response-example.json
{
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/3YAldML4EDyoC6RBpzceALigrAZ.jpg",
      "genre_ids": [
        18
      ],
      "id": 9300,
      "original_language": "en",
      "original_title": "Orlando",
      "overview": "England, 1600. Queen Elizabeth I promises Orlando, a young nobleman obsessed with poetry, that she will grant him land and fortune if he agrees to satisfy a very particular request.",
      "popularity": 7.768,
      "poster_path": "/xvz0qZkXXMq3dH2Revxii8drxWc.jpg",
      "release_date": "1992-12-11",
      "title": "Orlando",
      "video": false,
      "vote_average": 6.966,
      "vote_count": 262
    }
  ],
  "total_pages": 364,
  "total_results": 7269
}

=== api-evangelist/tmdb/examples/tmdb-api-account-watchlist-movies-response-example.json
{
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/rgNzvSagnlc32TuMEBa529QFIig.jpg",
      "genre_ids": [
        878
      ],
      "id": 76726,
      "original_language": "en",
      "original_title": "Chronicle",
      "overview": "Three high school students make an incredible discovery, leading to their developing uncanny powers beyond their understanding. As they learn to control their abilities and use them to their advantage, their lives start to spin out of control, and their darker sides begin to take over.",
      "popularity": 37.148,
      "poster_path": "/xENglsVIIWEEhhB5lgpy33tGcKI.jpg",
      "release_date": "2012-02-01",
      "title": "Chronicle",
      "video": false,
      "vote_average": 6.822,
      "vote_count": 4741
    }
  ],
  "total_pages": 34,
  "total_results": 677
}

=== api-evangelist/tmdb/examples/tmdb-api-trending-people-response-example.json
{
  "page": 1,
  "results": [
    {
      "adult": false,
      "id": 224513,
      "name": "Ana de Armas",
      "original_name": "Ana de Armas",
      "media_type": "person",
      "popularity": 349.766,
      "gender": 1,
      "known_for_department": "Acting",
      "profile_path": "/3vxvsmYLTf4jnr163SUlBIw51ee.jpg",
      "known_for": [
        {
          "adult": {},
          "backdrop_path": {},
          "id": {},
          "title": {},
          "original_language": {},
          "original_title": {},
          "overview": {},
          "poster_path": {},
          "media_type": {},
          "genre_ids": {},
          "popularity": {},
          "release_date": {},
          "video": {},
          "vote_average": {},
          "vote_count": {}
        }
      ]
    }
  ],
  "total_pages": 1000,
  "total_results": 20000
}

=== api-evangelist/tmdb/examples/tmdb-api-account-rated-movies-response-example.json
{
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/dUVbWINfRMGojGZRcO6GF1Z2nV8.jpg",
      "genre_ids": [
        12
      ],
      "id": 120,
      "original_language": "en",
      "original_title": "The Lord of the Rings: The Fellowship of the Ring",
      "overview": "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
      "popularity": 84.737,
      "poster_path": "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
      "release_date": "2001-12-18",
      "title": "The Lord of the Rings: The Fellowship of the Ring",
      "video": false,
      "vote_average": 8.396,
      "vote_count": 22579,
      "rating": 8
    }
  ],
  "total_pages": 47,
  "total_results": 940
}

=== api-evangelist/tmdb/examples/tmdb-api-guest-session-rated-tv-response-example.json
{
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
      "genre_ids": [
        10765
      ],
      "id": 1399,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Game of Thrones",
      "overview": "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      "popularity": 404.299,
      "poster_path": "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
      "first_air_date": "2011-04-17",
      "name": "Game of Thrones",
      "vote_average": 8.436,
      "vote_count": 21025,
      "rating": 8.5
    }
  ],
  "total_pages": 1,
  "total_results": 1
}
